### PR TITLE
Replace references to SMWElasticStore with SMW\Elastic\ElasticStore

### LINKED ISSUE #6057: Error: There is no backend class "SMWElasticStore". Aborting.
### Setup

- SMW version: 5.0.0-beta
- MW version: 1.43.0
- PHP version: 8.1
- DB system (MySQL, Blazegraph, etc.) and version: 
- Elasticsearch: 7.10.2

### Issue

When running `setupStore.php`:

```
root@cb06067dc3cc:/var/www/html# php w/maintenance/run SemanticMediaWiki:setupStore.php
Deprecated: Use of MediaWiki\Maintenance\Maintenance::error( $err, $die ) was deprecated in MediaWiki 1.31. [Called from SMW\Maintenance\setupStore::getStore in /var/www/html/w/extensions/SemanticMediaWiki/maintenance/setupStore.php at line 206] in /var/www/html/w/includes/debug/MWDebug.php on line 385

Error: There is no backend class "SMWElasticStore". Aborting.
```

I have

```php
$smwgDefaultStore = 'SMWElasticStore';
```

in `LocalSettings.php`

### PR DESCRIPTION
**Pull request by paladox**
Fixes #6057

## Summary by CodeRabbit

- **Chores**
  - Updated the default store identifier throughout the application to a fully qualified, namespaced format.
- **Documentation**
  - Revised configuration instructions to reflect the new, namespaced store reference.
- **Tests**
  - Adjusted test configurations to align with the updated default store value.

### CODE REVIEW

File: src/MediaWiki/Search/ProfileForm/ProfileForm.php [hunk 1]
```diff
@@ -351,7 +351,7 @@ private function buildSortForm( $request ) {
 		// TODO this information should come from the store and not being
 		// derived from a class! How should such characteristic be represented?
 		$features = [
-			'best' => is_a( $this->store, "SMWElasticStore" )
+			'best' => is_a( $this->store, "SMW\Elastic\ElasticStore" )
```
Comment (paladox) [inline src/MediaWiki/Search/ProfileForm/ProfileForm.php:354]: Not sure if I did this correctly. Think I did.

**Review by jaideraf — APPROVED** [review]

**Comment by paladox** [comment]
Bump :)
