### PR TITLE
[SMWSearch] Allow `callable` in `$smwgFallbackSearchType`, refs 3937, 3939

### LINKED ISSUE #3939: SMWSearch: TypeError from line 107 in "CirrusSearch.php"
### Setup and configuration

- MediaWiki | 1.32.1 (3efaceb)17:46, 11. Apr. 2019
- PHP | 7.2.15-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.38-MariaDB-0ubuntu0.18.04.1
- Elasticsearch | 6.5.4
- Semantic MediaWiki | 3.1.0-alpha (a795e69) 17:50, 15. Apr. 2019
- CirrusSearch | 0.2 (3bcae30) 18:19, 18. Apr. 2019

### Issue
If one would like to use CirrusSearch for searching with unstructured content I have to add the following configuration:
```php
$wgSearchType = 'SMWSearch';
$smwgFallbackSearchType = 'CirrusSearch';
```
However this leads to the following error:
```
[593268e934e3fe5abe2e7caf] /w/index.php?search=article&title=Sp%C3%A9cial%3ARecherche&go=Seite TypeError from line 107 of /../w/extensions/CirrusSearch/includes/CirrusSearch.php: Argument 1 passed to CirrusSearch::__construct() must be an instance of CirrusSearch\SearchConfig or null, instance of Wikimedia\Rdbms\DatabaseMysqli given, called in /../w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Search.php on line 114
```
See [line 107 of /../w/extensions/CirrusSearch/includes/CirrusSearch.php](https://github.com/wikimedia/mediawiki-extensions-CirrusSearch/blob/master/includes/CirrusSearch.php#L107)

### Stack trace
Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and/or outputs:

```
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Search.php(114): CirrusSearch->__construct(Wikimedia\Rdbms\DatabaseMysqli)
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Search/Search.php(402): SMW\MediaWiki\Search\Search->getFallbackSearchEngine()
#2 /../w/includes/specials/SpecialSearch.php(311): SMW\MediaWiki\Search\Search->setFeatureData(string, boolean)
#3 /../w/includes/specials/SpecialSearch.php(190): SpecialSearch->showResults(string)
#4 /../w/includes/specialpage/SpecialPage.php(569): SpecialSearch->execute(NULL)
#5 /../w/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#6 /../w/includes/MediaWiki.php(288): MediaWiki\Special\SpecialPageFactory->executePath(Title, RequestContext)
#7 /../w/includes/MediaWiki.php(860): MediaWiki->performRequest()
#8 /../w/includes/MediaWiki.php(517): MediaWiki->main()
#9 /../w/index.php(42): MediaWiki->run()
#10 {main}
```
@s7eph4n It would have been really cool to have this working. I just pray that this can be solved on the side of SMW somehow since I do not have high hopes for fixes in CirrusSearch.

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #3937, #3939

This PR addresses or contains:

- Support `callable` in `$smwgFallbackSearchType`

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #3939

### Examples

```
$smwgFallbackSearchType = function( $connection ) {
	return new \SearchMySQL( $connection );
};
```
```
$smwgFallbackSearchType = function() {
	return new \CirrusSearch();
};
```

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln Please test.

File: src/MediaWiki/Search/Search.php [hunk 1]
```diff
@@ -471,4 +446,52 @@ public function setShowSuggestion( $showSuggestion ) {
...
+		$applicationFactory = ApplicationFactory::getInstance();
+		$type = $applicationFactory->getSettings()->get( 'smwgFallbackSearchType' );
+
+		$connection = $this->getDB();
+
+		if ( is_callable( $type ) ) {
+			// #3939
+			$fallbackSearch = $type( $connection );
+		} elseif ( $type !== null && $this->isValidFallbackSearchEngineType( $type ) ) {
+			$fallbackSearch = new $type( $connection );
```
Comment (s7eph4n) [inline src/MediaWiki/Search/Search.php]: This could still lead to a crash.
Using a string for `$smwgFallbackSearchType` is still possible and `isValidFallbackSearchEngineType()` will allow any subclass of `SearchEngine`, including those where the constructor does not take a DB connection as parameter (e.g. CirrusSearch).
I see two ways: 1. Check for `!is_subclass_of( $type, 'SearchDatabase' )` in `isValidFallbackSearchEngineType()` or 2. just wrap the `new $type( $connection )` in a try-catch.

Comment (mwjames) [reply src/MediaWiki/Search/Search.php]: Yes, so maybe:

- Check for `!is_subclass_of( $type, 'SearchDatabase' )` in isValidFallbackSearchEngineType()
- Rename `isValidFallbackSearchEngineType` to `isValidFallbackSearchDatabaseType`

**Comment by kghbln** [comment]
Cool, I just successfully tested with:

```php
$smwgFallbackSearchType = function() {
	return new \CirrusSearch();
};
```

I am not sure about how to explain the second configuration example. When to use this one:
```php
$smwgFallbackSearchType = function( $connection ) {
	return new \SearchMySQL( $connection );
};
```

**Comment by mwjames** [comment]
> I am not sure about how to explain the second configuration example. When to use this one:

Normally you don't need that one (`SearchMySQL`) and it should demonstrate how to use the "callback" besides `CirrusSearch`.
