### PR TITLE
ChangePropagationDispatchJob: Don't presume job will be run on same server

### LINKED ISSUE #5929: ChangePropagationDispatchJob: Fix tmp files
### Setup

- SMW version: master
- MW version: 1.42
- PHP version: 8.2
- DB system (MySQL, Blazegraph, etc.) and version: Mariadb 10.11

### Issue

I'm not entirely sure how to reproduce but based on what I see, smw_chgprop_ is failing to be found. We moved to the new modern job runner (kafka/changeprop/eventgate) and use haproxy to randomly sends requests to a mw server so things don't become overloaded. So I think the problem is a new job is created after the tmp file is created but of course that will be ran on another mw servers because of the random setting we have set.

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2fcc99a762189282f6fd6e1e3a89db29f1e2c4ea/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php#L263

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2fcc99a762189282f6fd6e1e3a89db29f1e2c4ea/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php#L284

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2fcc99a762189282f6fd6e1e3a89db29f1e2c4ea/src/MediaWiki/Jobs/ChangePropagationDispatchJob.php#L293

Unless we set things up wrong which I don't think we have? (I mean with the changeprop/kafka setup).

### PR DESCRIPTION
**Pull request by paladox**
Fixes support for change propagation (wikimedia new job runner). Don't presume a job will run on the same server. So instead of creating temp files, we just pass the contents as a param.

Fixes #5929

## Summary by CodeRabbit

- **Refactor**
	- Streamlined background processing by switching from temporary file reliance to direct data handling for improved efficiency.
	- Updated data input methods to simplify operations and enhance processing reliability.
	- Simplified checksum verification by computing directly from data input.
	- Notable removal of parameters related to temporary files in job execution.

- **Tests**
	- Removed mock handling of temporary files in test cases, simplifying the testing process.

- **Documentation**
	- Added a "Breaking changes" section to release notes, highlighting the removal of parameters and changes in data handling for the `ChangePropagationDispatchJob`.

### CODE REVIEW

**Comment by paladox** [comment]
When reviewing please note this is untested so please make sure I did it correctly.

All I wanted to do was instead of creating temp files that stored the content, we just supply the contents to the param.

**Comment by paladox** [comment]
@coderabbitai review

File: src/MediaWiki/Jobs/ChangePropagationDispatchJob.php [hunk 1]
```diff
@@ -190,8 +190,8 @@ public static function getPendingJobsCount( DIWikiPage $subject ) {
 	public function run() {
 		$subject = DIWikiPage::newFromTitle( $this->getTitle() );
 
-		if ( $this->hasParameter( 'dataFile' ) ) {
-			return $this->dispatchFromFile( $subject, $this->getParameter( 'dataFile' ) );
+		if ( $this->hasParameter( 'data' ) ) {
```
Comment (JeroenDeDauw) [inline src/MediaWiki/Jobs/ChangePropagationDispatchJob.php:193]: This looks like a breaking change that needs documenting in https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-5.0.0.md

File: src/MediaWiki/Jobs/ChangePropagationDispatchJob.php [hunk 2]
```diff
@@ -258,43 +258,31 @@ private function findAndDispatch() {
...
+			$this->pushChangePropagationDispatchJob( $i++, $chunk );
 		}
 	}
 
-	private function pushChangePropagationDispatchJob( $tempFile, $file, $num, $chunk ) {
+	private function pushChangePropagationDispatchJob( $num, $chunk ) {
 		$data = [];
-		$file .= "_$num.tmp";
+		// Used as a job key
+		$file = "smw_chgprop_$num\_tmp";
```
[the remark this answers is not in the document]
Comment (paladox) [reply src/MediaWiki/Jobs/ChangePropagationDispatchJob.php]: Thanks, done.

File: src/MediaWiki/Jobs/ChangePropagationDispatchJob.php (hunk 1 above)
Comment (paladox) [reply src/MediaWiki/Jobs/ChangePropagationDispatchJob.php:193]: Thanks, done.

File: src/MediaWiki/Jobs/ChangePropagationDispatchJob.php [hunk 3]
```diff
@@ -284,7 +282,7 @@ private function pushChangePropagationDispatchJob( $num, $chunk ) {
 			[
 				'data' => $contents
 			] + self::newRootJobParams(
-				"ChangePropagationDispatchJob:$file:$checkSum"
+				"ChangePropagationDispatchJob:smw_chgprop_$num\_tmp:$checkSum"
```
Comment (JeroenDeDauw) [inline src/MediaWiki/Jobs/ChangePropagationDispatchJob.php:285]: I am wondering why the backslash is there

Comment (paladox) [reply src/MediaWiki/Jobs/ChangePropagationDispatchJob.php:285]: Because a variable can contain an underscore and so it was acting like $num_tmp was a variable.
