### PR TITLE
Fix TypeError in Rebuilder when handling DB rows

### LINKED ISSUE #6651: Rebuilder::hasSkippableRevision(): Argument #2 ($row) must be of type bool
### Setup

- SMW version: * dev-master, * 7.x-dev released : 2026-04-17
- MW version: 1.45.3
- PHP version: 8.2
- DB system (MySQL, Blazegraph, etc.) and version: 8.0.41-0ubuntu0.24.04.1

### Issue
When I run "php maintenance/run.php SemanticMediaWiki:rebuildData" I get the following error; I get it for different articles on 4 of my wikis I tried it on: 

```Rebuilding semantic data ...
   ... selecting 1 to 196986 IDs ...
   ... updating ...                                     749 / 196986 (  0%)[48fa837c953d0343701c905d] [no req]   TypeError: SMW\SQLStore\Rebuilder\Rebuilder::hasSkippableRevision(): Argument #2 ($row) must be of type bool, stdClass given, called in <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php on line 445
Backtrace:
from <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(429)
#0 <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(445): SMW\SQLStore\Rebuilder\Rebuilder->hasSkippableRevision(MediaWiki\Title\Title, stdClass)
#1 <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(324): SMW\SQLStore\Rebuilder\Rebuilder->addJob(MediaWiki\Title\Title, stdClass)
#2 <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(277): SMW\SQLStore\Rebuilder\Rebuilder->checkRow(stdClass)
#3 <wiki folder>/extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(185): SMW\SQLStore\Rebuilder\Rebuilder->matchAsSubject(int, bool)
#4 <wiki folder>/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(434): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(int)
#5 <wiki folder>/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(352): SMW\Maintenance\DataRebuilder->doUpdateById(int)
#6 <wiki folder>/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(193): SMW\Maintenance\DataRebuilder->rebuildAll()
#7 <wiki folder>/extensions/SemanticMediaWiki/maintenance/rebuildData.php(202): SMW\Maintenance\DataRebuilder->rebuild()
#8 <wiki folder>/maintenance/includes/MaintenanceRunner.php(696): SMW\Maintenance\rebuildData->execute()
#9 <wiki folder>/maintenance/run.php(53): MediaWiki\Maintenance\MaintenanceRunner->run()
#10 {main}
```

### PR DESCRIPTION
**Pull request by alistair3149**
## Summary

Fixes #6651. `php maintenance/run.php SemanticMediaWiki:rebuildData` aborts with a `TypeError` as soon as it dispatches a non-skipped entity.

## Root cause

`Rebuilder::hasSkippableRevision()` was typed as `bool $row = false`, but the callers pass a `stdClass` DB row from `SQLStore::ID_TABLE`:

```
matchAsSubject() → checkRow(stdClass) → addJob(Title, stdClass)
                                     → hasSkippableRevision(Title, stdClass)  💥
```

The `bool` type was introduced by automated type inference in #6505 — it picked up `bool` from the `= false` default without checking what callers actually pass. The real contract for `$row` is `stdClass|false` — `false` is a legacy sentinel meaning \"no pre-fetched row\", otherwise it's a DB result object whose `smw_rev` is compared against the latest revision.

## Fix

Correct the type on three correlated signatures:
- `Rebuilder::hasSkippableRevision()`
- `Rebuilder::addJob()`
- `EntityValidator::hasLatestRevID()`

## Test plan

- [x] `composer analyze` clean on changed files
- [x] `tests/phpunit/Unit/SQLStore/Rebuilder/` — 10/10 pass
- [ ] Manual: run `rebuildData` on a wiki with existing pages and confirm no `TypeError`

### CODE REVIEW

File: src/SQLStore/Rebuilder/Rebuilder.php [hunk 1]
```diff
@@ -426,7 +427,7 @@ private function next_position( &$id, bool $emptyRange ): void {
 		$id = $nextPosition ?: -1;
 	}
 
-	private function hasSkippableRevision( $title, bool $row = false ): bool {
+	private function hasSkippableRevision( $title, stdClass|false $row = false ): bool {
```
Comment (paladox) [inline src/SQLStore/Rebuilder/Rebuilder.php:430]: I think this has to be stdClass|bool because apparently false type will fail on php 8.1.

Comment (alistair3149) [reply src/SQLStore/Rebuilder/Rebuilder.php:430]: `false` is not allowed as a standalone type in PHP 8.1 but it is allowed in an union type since PHP 8.0.
https://wiki.php.net/rfc/union_types_v2
