### PR TITLE
CustomForm: Fix "Trying to access array offset on value of type null "

### LINKED ISSUE #5644: Notice: Trying to access array offset on value of type null in CustomForm.php on line 131
### Setup

- MediaWiki | 1.39.7 (64425c7)16:12, 15 May 2024
- PHP | 7.4.33 (apache2handler)
- MariaDB | 10.5.23-MariaDB-0+deb11u1
- Elasticsearch | 7.10.2
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.3

### Issue
Happening on https://sandbox.semantic-mediawiki.net/

When trying to search for something on "Special:Search" I get:

```
 Notice: Trying to access array offset on value of type null in /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php on line 131
```

### PR DESCRIPTION
**Pull request by paladox**
This happens because ->getArray() can return null if it can't find the key. We fix this by instead changing the return default for getArray to an array. We then change the isset check to use new php syntax and also return a null, instead of using $vals[0]. We already check for that so this was a duplicate and was error prone.

Fixes #5644

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved form input handling to ensure that when no values are found, an empty array is returned, enhancing robustness in form processing.
	- Simplified logic for value assignment in forms, improving clarity and reducing potential errors in data handling.

### CODE REVIEW

File: src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php [hunk 1]
```diff
@@ -122,10 +122,10 @@ public function makeFields( $definition ) {
 
 			// Find request related value for the active form
 			if ( $this->isActiveForm ) {
-				$vals = $this->request->getArray( $name );
+				$vals = $this->request->getArray( $name, [] );
 
 				$i = $this->fieldCounter[$name];
-				$value = isset( $vals[$i] ) ? $vals[$i] : $vals[0];
+				$value = $vals[$i] ?? null;
```
Comment (paladox) [inline src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php:128]: I'm not sure if this should be '' instead of null.

File: src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php [hunk 2]
```diff
@@ -66,7 +66,7 @@ public function __construct( WebRequest $request ) {
 	/**
 	 * @since 3.0
 	 *
-	 * @return
+	 * @return array
 	 */
 	public function getParameters() {
```
Comment (alistair3149) [inline src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php:71]: We can put a type declaration here and drop the `@return` doc

Comment (paladox) [reply src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php:71]: do you mean like `: array {`?

File: src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php (hunk 1 above)
Comment (alistair3149) [reply src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php:128]: Should be just `''` because it was the previous value on line 106

File: src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php (hunk 2 above)
Comment (paladox) [reply src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php]: Thanks, done.

File: src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php (hunk 1 above)
Comment (paladox) [reply src/MediaWiki/Search/ProfileForm/Forms/CustomForm.php]: Thanks, done.
