### PR TITLE
Use `Maintenance::getDB` in `setupStore.php`, refs 2963

### LINKED ISSUE #2963: setupStore.php: Use wgDBadminuser instead wgDBuser
When setting $wgDBadminuser and -password in LocalSetttings.php the setupStore.php maintenance script, should use these instead of $wgDBuser and -password, as its done by native MediaWiki maintenance scripts, c.f. https://www.mediawiki.org/wiki/Manual:$wgDBadminuser .

### Steps to reproduce
configure remove CREATE TABLE, etc. rights from the mysql user your semantic mediawiki is using, and try to install/upgrade semantic mediawiki -> Tables does not get created.

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2963

This PR addresses or contains:

- Adds `CallbackConnectionProvider`
- Uses `Maintenance::getDB` in `setupStore.php` which is expected to address #2963 (`$wgDBadminuser` issue) but has not explicitly tested whether this resolves it or not

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #2963

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln This passes the test suite which means it should be safe to use whether it addresses the `$wgDBadminuser` issue or not but it would be good to confirm the assumption somehow.

File: maintenance/setupStore.php [hunk 1]
```diff
@@ -111,6 +113,24 @@ public function execute() {
...
+
+		$connectionManager->registerConnectionProvider(
+			DB_MASTER,
+			$callbackConnectionProvider
+		);
+
+		$store->setConnectionManager(
+			$connectionManager
+		);
+
```
Comment (JeroenDeDauw) [inline maintenance/setupStore.php]: Looks like this should be a single function. No need to have these two new variables in scope longer, or to access the ones already in scope. Plus this function is already very long, with lots of random details (thus mixed levels of abstractions) in it.

File: src/Connection/CallbackConnectionProvider.php [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+	 * @param Closure $callback
+	 */
+	public function __construct( Closure $callback ) {
+		$this->callback = $callback;
+	}
+
+	/**
+	 * @since 3.0
+	 *
+	 * @return mixed
```
Comment (JeroenDeDauw) [inline src/Connection/CallbackConnectionProvider.php]: Should this not be a connection thing?

File: src/Connection/CallbackConnectionProvider.php [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+	 * @var mixed
+	 */
+	private $connection;
+
+	/**
+	 * @since 3.0
+	 *
+	 * @param Closure $callback
+	 */
+	public function __construct( Closure $callback ) {
```
Comment (JeroenDeDauw) [inline src/Connection/CallbackConnectionProvider.php]: `callable` is less restrictive and has no downsides as far as I know

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+			CallbackConnectionProvider::class,
+			new CallbackConnectionProvider( $callback )
+		);
+	}
+
+	public function testGetConnection() {
+
+		$connection = $this->getMockBuilder( '\stdClass' )
+			->disableOriginalConstructor()
+			->getMock();
```
Comment (JeroenDeDauw) [inline tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: huh?! This is the same as `$connection = new \stdClass()` no?

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php [hunk 5]
```diff
@@ -0,0 +1,48 @@
...
+
+	public function testCanConstruct() {
+
+		$callback = function() {};
+
+		$this->assertInstanceOf(
+			CallbackConnectionProvider::class,
+			new CallbackConnectionProvider( $callback )
+		);
+	}
```
Comment (JeroenDeDauw) [inline tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: IMO this does not add value and is thus harmful clutter. (Yes I realize I introduced the first tests like this in the codebase, this was a mistake)

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+
+	public function testGetConnection() {
```
Comment (JeroenDeDauw) [inline tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: This is not a descriptive name. I suggest doing something like `testGetConnectionReturnsTheCallbacksReturnValue`.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 4 above)
Comment (JeroenDeDauw) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: Also beware that this PHPUnit syntax is not compatible with the latest versions of PHPUnit. I don't know if it is easy to switch to using a more recent version of PHPUnit (with SMW being a MW extension and all...), though if possible, doing this sooner rather than later will save migration work.

File: src/Connection/CallbackConnectionProvider.php (hunk 2 above)
Comment (mwjames) [reply src/Connection/CallbackConnectionProvider.php]: No, it is a generic callback therefore you type. The invoker is responsible to make the right choice.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 4 above)
Comment (mwjames) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: This should work in any version, or? and if not what changed?

> to switch to using a more recent version of PHPUnit (with SMW being a MW extension and all...)

2713 has the details!

**Comment by mwjames** [comment]
> Also beware that you did not test most of the new code (the new test only covers arguably the simplest addition)

That is not true,it is covered by the integration test.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 6 above)
Comment (mwjames) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: Feel free to changed it, it works for me.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 5 above)
Comment (mwjames) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: It works for me!

File: src/Connection/CallbackConnectionProvider.php (hunk 3 above)
Comment (mwjames) [reply src/Connection/CallbackConnectionProvider.php]: Yes, but nothing is wrong with `Closure` and it doesn't impose a functional impairment.

Comment (JeroenDeDauw) [reply src/Connection/CallbackConnectionProvider.php]: It does: you can only provide Closures like this. You can't pass in 'globalFunctionName', 'SomeClass::staticFunction' or $instanceOfClassThatIsCallable

File: src/Connection/CallbackConnectionProvider.php (hunk 2 above)
Comment (JeroenDeDauw) [reply src/Connection/CallbackConnectionProvider.php]: I understand that this function cannot guarantee the type that is returned. Though I think this does not really matter for the return type. The return type is about indicating what it should return. Of course this should match what the callback is supposed to return. Unless I am misunderstanding the code, in both cases this should be a connection, whatever a connection is. Weirdly enough the ConnectionProvider interface does not mention a specific type. Is that understanding wrong?

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 6 above)
Comment (JeroenDeDauw) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: I'm not set on having this particular bit of code look one way or the other. What I am doing here with my time is giving you some advice, which you are of course free to ignore. Naming your test methods badly indeed "will work". Naming them more descriptive will work better, both for yourself, and to a bigger degree for other people. Not writing any tests also "will work". I recall giving advice to this one specific contributor several years ago that writing tests is a good idea, and at first getting a bunch of outraged "oh, so now I need to write tests for everything?!". I was happy to see this person changed their mind, wrote a lot of tests, and now encourages other people to do the same. If they had stayed at "it works for me", that'd have been a shame.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 4 above)
Comment (JeroenDeDauw) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2713

Comment (JeroenDeDauw) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: Oh... actually this might indeed *work* in the latest PHPUnit. I'm not sure as I have not used this format recently. Which is because it does not make sense to use this form there. You'd just do `$connection = $this->createMock( '\stdClass' )`

At least you would if there was reason to use the mock API. Why not just create the instance like in my first comment?

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 6 above)
Comment (mwjames) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: Let not mix functional relevancy (which is to use a unit test to verify that what is expected can actually be asserted) with cosmetic preference which the later is about. We do agree that descriptive names may help others to understand the code in question but for a class with one single responsibility we don't have go in circles here and keep discussing a dead horse.

File: src/Connection/CallbackConnectionProvider.php (hunk 3 above)
Comment (mwjames) [reply src/Connection/CallbackConnectionProvider.php]: Right, yes that is the only valid functional argument I have seen in this thread that should be reconsidered to allow for something like [ $this, '...' ]. [0] requires PHP 5.4 which is fine given that min req. is PHP 5.5.

[0] http://php.net/manual/de/language.types.callable.php

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 5 above)
Comment (mwjames) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: > harmful clutter

Disagree, this allows to check whether the constructor does work or not.

**Comment by mwjames** [comment]
@kghbln Would be nice if you could test this with the `wgDBadminuser` user thing as I'd like to finish this up.

File: tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php (hunk 6 above)
Comment (JeroenDeDauw) [reply tests/phpunit/Unit/Connection/CallbackConnectionProviderTest.php]: So you are saying that in classes with a single responsibility good naming is not important as long as the classes do their job? And also that I am wasting my time even bringing this up?

**Comment by JeroenDeDauw** [comment]
> That is not true,it is covered by the integration test.

What integration test? One that was already there? That verify the correctness of the new code if it was already there and did not fail before the new code was added. In such a case you could refactor the code, accidentally break the new behavior, and still have the test passing.

**Comment by kghbln** [comment]
> Would be nice if you could test this with the wgDBadminuser user thing as I'd like to finish this up.

I will switch sandbox today. Will it be possible to back-port this to 2.5.x once I confirmed it is working on master?

**Comment by kghbln** [comment]
@mwjames The field test just failed. "setupStore.php" still uses user and password defined with `$wgDBuser` and `$wgDBpassword` respectively. `$wgDBadminuser` and `$wgDBadminpassword` also defined is being ignored.

**Comment by mwjames** [comment]
> The field test just failed. "setupStore.php" still uses user and password defined

Well. after browsing the `Maintenance` class it became clear that we need to set `\Maintenance::DB_ADMIN` to force a preference for the `admin` related user.

**Comment by kghbln** [comment]
> Well. after browsing the `Maintenance` class it became clear that we need to set `\Maintenance::DB_ADMIN` to force a preference for the `admin` related user.

No worries and thanks for the fix. I will do another field test after the next update on sandbox.

**Comment by kghbln** [comment]
> I will do another field test after the next update on sandbox.

Works perfect now. Thanks a lot!
