### PR TITLE
Fix "Call to undefined method SMWDIError::getJD()"

### LINKED ISSUE #3598: Error from line 306 in "RecurringEvents.php": Call to undefined method SMWDIError::getJD()
### Setup and configuration

- MediaWiki | 1.32.0 (0fbb878)23:05, 10. Jan. 2019
- PHP | 7.0.33-0+deb9u1 (apache2handler)
- MariaDB | 10.1.37-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.1.0-alpha (9c19d87) 10:17, 7. Jan. 2019

### Issue
```
[6585d43e04160c2a723783e7] /w/index.php?title=Issue/3541/2&action=submit Error from line 306 of /.../w/extensions/SemanticMediaWiki/includes/RecurringEvents.php: Call to undefined method SMWDIError::getJD()
```

### Stack trace
```
#0 /.../w/extensions/SemanticMediaWiki/includes/RecurringEvents.php(61): SMW\RecurringEvents->parse(array)
#1 /.../w/extensions/SemanticMediaWiki/src/ParserFunctions/RecurringEventsParserFunction.php(122): SMW\RecurringEvents->__construct(array)
#2 /.../w/extensions/SemanticMediaWiki/src/ParserFunctions/RecurringEventsParserFunction.php(79): SMW\ParserFunctions\RecurringEventsParserFunction->initRecurringEvents(array)
#3 /.../w/extensions/SemanticMediaWiki/src/ParserFunctionFactory.php(452): SMW\ParserFunctions\RecurringEventsParserFunction->parse(SMW\ParserParameterProcessor)
#4 /.../w/includes/parser/Parser.php(3493): SMW\ParserFunctionFactory->SMW\{closure}(Parser, string, string, string, string)
#5 /.../w/includes/parser/Parser.php(3200): Parser->callParserFunction(PPFrame_DOM, string, array)
#6 /.../w/includes/parser/Preprocessor_DOM.php(1279): Parser->braceSubstitution(array, PPFrame_DOM)
#7 /.../w/includes/parser/Parser.php(3014): PPFrame_DOM->expand(DOMElement, integer)
#8 /.../w/includes/parser/Parser.php(1350): Parser->replaceVariables(string)
#9 /.../w/includes/parser/Parser.php(476): Parser->internalParse(string)
#10 /.../w/includes/content/WikitextContent.php(341): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#11 /.../w/includes/content/AbstractContent.php(517): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#12 /.../w/includes/Revision/RenderedRevision.php(242): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#13 /.../w/includes/Revision/RenderedRevision.php(211): MediaWiki\Revision\RenderedRevision->getSlotParserOutputUncached(WikitextContent, boolean)
#14 /.../w/includes/Revision/RevisionRenderer.php(175): MediaWiki\Revision\RenderedRevision->getSlotParserOutput(string)
#15 /.../w/includes/Revision/RevisionRenderer.php(128): MediaWiki\Revision\RevisionRenderer->combineSlotOutput(MediaWiki\Revision\RenderedRevision, array)
#16 [internal function]: MediaWiki\Revision\RevisionRenderer->MediaWiki\Revision\{closure}(MediaWiki\Revision\RenderedRevision, array)
#17 /.../w/includes/Revision/RenderedRevision.php(175): call_user_func(Closure, MediaWiki\Revision\RenderedRevision, array)
#18 /.../w/includes/Storage/DerivedPageDataUpdater.php(1265): MediaWiki\Revision\RenderedRevision->getRevisionParserOutput()
#19 /.../w/includes/Storage/DerivedPageDataUpdater.php(1235): MediaWiki\Storage\DerivedPageDataUpdater->getCanonicalParserOutput()
#20 /.../w/includes/page/WikiPage.php(1994): MediaWiki\Storage\DerivedPageDataUpdater->getPreparedEdit()
#21 /.../w/extensions/SpamBlacklist/includes/SpamBlacklistHooks.php(31): WikiPage->prepareContentForEdit(WikitextContent)
#22 /.../w/includes/Hooks.php(174): SpamBlacklistHooks::filterMergedContent(RequestContext, WikitextContent, Status, string, User, boolean)
#23 /.../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#24 /.../w/includes/EditPage.php(1747): Hooks::run(string, array)
#25 /.../w/includes/EditPage.php(2066): EditPage->runPostMergeFilters(WikitextContent, Status, User)
#26 /.../w/includes/EditPage.php(1574): EditPage->internalAttemptSave(NULL, boolean)
#27 /.../w/includes/EditPage.php(677): EditPage->attemptSave(NULL)
#28 /.../w/includes/actions/EditAction.php(60): EditPage->edit()
#29 /.../w/includes/actions/SubmitAction.php(38): EditAction->show()
#30 /.../w/includes/MediaWiki.php(501): SubmitAction->show()
#31 /.../w/includes/MediaWiki.php(294): MediaWiki->performAction(Article, Title)
#32 /.../w/includes/MediaWiki.php(860): MediaWiki->performRequest()
#33 /.../w/includes/MediaWiki.php(517): MediaWiki->main()
#34 /.../w/index.php(42): MediaWiki->run()
#35 {main}
```

### Steps to reproduce
Trying to add something like
```
{{#set_recurring_event: Is team meeting |property=Has date |start=30 janvier 2019 9:30 am |unit=month }}
```
or
```
{{#set_recurring_event: Is team meeting |property=Has date |start=31 janvier 2019 9:30 am |unit=month }}
```
will cause the issue.

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3598 

This PR addresses or contains:
- Fixes `#set_recurring_event:` causing "Call to undefined method SMWDIError::getJD()" as suggested by @mwjames in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3598#issuecomment-453756673

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #3598

### CODE REVIEW

File: includes/RecurringEvents.php [hunk 1]
```diff
@@ -305,6 +307,10 @@ public function parse( array $parameters ) {
 					$new_month = 12;
 				}
 
+				if ( $cur_date->isValid() ) {
```
Comment (mwjames) [inline includes/RecurringEvents.php]: Remove line 310-313 which were added by the PR!

**Comment by kghbln** [comment]
> You somehow added more than there was before!

Nope, this is an exact copy of what I did before. However these lines can be deleted.

**Comment by mwjames** [comment]
> Nope, this is an exact copy of what I did before. However these lines can be deleted.

You added those lines which weren't there before only line `$cur_date_jd = $cur_date->getDataItem()->getJD();` was the issue.

**Comment by kghbln** [comment]
Back-ported with 4d9e5a76e39244344b466682673fcf5e57b4f679
