### PR TITLE
Fix #5634 MW 1.42 DBAL compatibility

### LINKED ISSUE #5634: MediaWiki 1.43 DBAL compatibility
### Setup

- SMW version: master branch at #f6b3855f
- MW version: 1.43.0-wmf.2 (pre-release)
- PHP version: 8.1.20 (fpm-fcgi)
- DB system (MySQL, Blazegraph, etc.) and version: 10.11.4-MariaDB-1:10.11.4+maria~ubu2204

### Issue

During the Wikimedia Hackathon 2024, I tried to run the latest version of Semantic MediaWiki on a pre-release version of MediaWiki 1.43 (upcomming LTS). The goal was to identify issues and maybe provide patches right away. Unfortunately, the available time will not allow to provide a fix, therefore I document the issue here. 

First: Installation (running `maintenance/run.php update`) and activation of the extension ran smoothly, No immediate error.

But when trying to access `Special:Browse` the API call with the parameters

```
action: smwbrowse
format: json
browse: subject
params: {"subject":"Main_Page","ns":0,"iw":"","subobject":"","options":{"dir":null,"lang":"en","group":null,"printable":null,"offset":null,"including":false,"showInverse":false,"showAll":true,"showGroup":true,"showSort":false,"api":true,"valuelistlimit.out":"30","valuelistlimit.in":"20"},"type":"html"}
```

failed with the error
```
Exception caught: Table name component contains unexpected quote or dot character

"Wikimedia\\Rdbms\\DBLanguageError at /includes/libs/rdbms/platform/SQLPlatform.php(1051)
from /includes/libs/rdbms/platform/SQLPlatform.php(1051)
#0 /includes/libs/rdbms/platform/SQLPlatform.php(991): Wikimedia\\Rdbms\\Platform\\SQLPlatform->extractTableNameComponents(string)
#1 /includes/libs/rdbms/platform/SQLPlatform.php(957): Wikimedia\\Rdbms\\Platform\\SQLPlatform->qualifiedTableComponents(string)
#2 /includes/libs/rdbms/platform/SQLPlatform.php(936): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableName(string)
#3 /includes/libs/rdbms/platform/SQLPlatform.php(837): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNameWithAlias(string, string)
#4 /includes/libs/rdbms/platform/SQLPlatform.php(666): Wikimedia\\Rdbms\\Platform\\SQLPlatform->tableNamesWithIndexClauseOrJOIN(array, array, array, array)
#5 /includes/libs/rdbms/database/Database.php(3335): Wikimedia\\Rdbms\\Platform\\SQLPlatform->selectSQLText(string, string, string, string, array, array)
#6 /includes/libs/rdbms/database/DatabaseMySQL.php(730): Wikimedia\\Rdbms\\Database->selectSQLText(string, string, string, string, array, array)
#7 /includes/libs/rdbms/database/Database.php(1342): Wikimedia\\Rdbms\\DatabaseMySQL->selectSQLText(string, string, string, string, array, array)
#8 /includes/libs/rdbms/database/DBConnRef.php(126): Wikimedia\\Rdbms\\Database->select(string, string, string, string, array, array)
#9 /includes/libs/rdbms/database/DBConnRef.php(358): Wikimedia\\Rdbms\\DBConnRef->__call(string, array)
#10 /extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(247): Wikimedia\\Rdbms\\DBConnRef->select(string, string, string, string, array, array)
#11 /extensions/SemanticMediaWiki/src/SQLStore/EntityStore/TraversalPropertyLookup.php(97): SMW\\MediaWiki\\Connection\\Database->select(string, string, string, string, array)
#12 /extensions/SemanticMediaWiki/src/SQLStore/EntityStore/EntityLookup.php(437): SMW\\SQLStore\\EntityStore\\TraversalPropertyLookup->fetchFromTable(SMW\\SQLStore\\PropertyTableDefinition, SMW\\DIWikiPage, SMW\\RequestOptions)
#13 /extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(289): SMW\\SQLStore\\EntityStore\\EntityLookup->getInProperties(SMW\\DIWikiPage, SMW\\RequestOptions)
#14 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(876): SMW\\SQLStore\\SQLStore->getInProperties(SMW\\DIWikiPage, SMW\\RequestOptions)
#15 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(355): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->getInData()
#16 /extensions/SemanticMediaWiki/src/MediaWiki/Specials/Browse/HtmlBuilder.php(263): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->createHTML()
#17 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(107): SMW\\MediaWiki\\Specials\\Browse\\HtmlBuilder->buildHTML()
#18 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse/SubjectLookup.php(69): SMW\\MediaWiki\\Api\\Browse\\SubjectLookup->buildHTML(array)
#19 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(268): SMW\\MediaWiki\\Api\\Browse\\SubjectLookup->lookup(array)
#20 /extensions/SemanticMediaWiki/src/MediaWiki/Api/Browse.php(71): SMW\\MediaWiki\\Api\\Browse->callSubjectLookup(array)
#21 /includes/api/ApiMain.php(1948): SMW\\MediaWiki\\Api\\Browse->execute()
#22 /includes/api/ApiMain.php(924): ApiMain->executeAction()
#23 /includes/api/ApiMain.php(895): ApiMain->executeActionWithErrorHandling()
#24 /includes/api/ApiEntryPoint.php(158): ApiMain->execute()
#25 /includes/MediaWikiEntryPoint.php(199): MediaWiki\\Api\\ApiEntryPoint->execute()
#26 /api.php(44): MediaWiki\\MediaWikiEntryPoint->run()
```

Apparently the code at

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/f6b3855f83faefb9c0f085486c0a2fd8f8a1f95a/src/SQLStore/EntityStore/TraversalPropertyLookup.php#L96-L102

gets called with `$from = "`smw_object_ids` INNER JOIN ( SELECT p_id FROM `smw_di_wikipage`  WHERE o_id=0  GROUP BY p_id ) AS t1 ON t1.p_id=smw_id"`, which is not allowed in the MediaWiki 1.43 DBAL anymore.

Wikimedia engineer Ladsgroup recommended to use the new "query builder" (in this particular case `SelectQueryBuilder`, see https://www.mediawiki.org/wiki/Manual:Database_access#SelectQueryBuilder) implementation of MediaWiki.

I can not tell how much code in Semantic MediaWiki is actually affected by this, but there are ~27 files that contain the `INNER JOIN` syntax.

### PR DESCRIPTION
**Pull request by Sheep-y**
Made compatible with MW 1.42 latest stable, retaining compatibility with 1.39 LTS.
* Rewrite QueryEngine (multiple class) to use Rdbms and workaround its issues.
* Reuse generic query generation for format=debug and format=count.
* Dynamic parameter for `ContentRenderer->getParserOutput` depending on MW version.
* Manually tested on MW 1.42.1, MW 1.39.8, PHP 7.4.33, PHP 8.3.9

Edit: Inner to Left join, as mentioned by CodeRabbit, is an existing feature in `ConceptCache->refresh()` for postgres compatibility; the rewrite use QuerySegment instead of string for joins, and a new method is written to recursively reproduce the same effect.

## Summary by CodeRabbit

- **Bug Fixes**
	- Modified logic for handling revision IDs to streamline operations while maintaining functionality.

- **Documentation**
	- Removed comments related to version checks to enhance code readability, though it may affect clarity regarding version dependencies.

### CODE REVIEW

File: src/MediaWiki/Connection/Database.php [hunk 1]
```diff
@@ -800,4 +800,37 @@ public function unescape_bytea( $text ) {
...
+	/**
+	 * Create and return a new SelectQueryBuilder from the read or write connection.
+	 *
+	 * @since 4.2
+	 *
+	 * @param string $mode 'read' or 'write'
+	 *
+	 * @return Wikimedia\Rdbms\SelectQueryBuilder
+	 */
+	public function newSelectQueryBuilder( $mode ) {
```
Comment (JeroenDeDauw) [inline src/MediaWiki/Connection/Database.php:812]: `public function newSelectQueryBuilder( string $mode ): SelectQueryBuilder {`

Comment (JeroenDeDauw) [reply src/MediaWiki/Connection/Database.php:812]: Which allows dropping the param and return docs in the comment

File: src/MediaWiki/Connection/Database.php [hunk 2]
```diff
@@ -800,4 +800,37 @@ public function unescape_bytea( $text ) {
...
+	 *
+	 * @return Wikimedia\Rdbms\SelectQueryBuilder
+	 */
+	public function applySqlOptions ( $builder, $sql_options ) {
+		if ( ! empty( $sql_options[ 'LIMIT' ]    ) ) $builder->limit  ( $sql_options[ 'LIMIT'    ] );
+		if ( ! empty( $sql_options[ 'OFFSET' ]   ) ) $builder->offset ( $sql_options[ 'OFFSET'   ] );
+		if ( ! empty( $sql_options[ 'GROUP BY' ] ) ) $builder->groupBy( $sql_options[ 'GROUP BY' ] );
+		if ( ! empty( $sql_options[ 'ORDER BY' ] ) ) $builder->orderBy( $sql_options[ 'ORDER BY' ] );
+		if ( isset( $sql_options[ 'DISTINCT' ] ) ) $builder->distinct();
+		return $builder;
```
[the remark this answers is not in the document]
Comment (JeroenDeDauw) [reply src/MediaWiki/Connection/Database.php:834]: Yup

**Comment by gesinn-it-gea** [comment]
We are currently renovating the CI framework and adding support up to MW 1.42. Maybe it's worth rebasing your PR as soon as new CI framework fixes arrive. If your changes will drop compat. with versions below 1.39, set support for those versions in the GH actions CI workflow to "experimental" or remove them. Btw. you can run the tests locally simply with a "make ci" command.

**Comment by JeroenDeDauw** [comment]
At this point it is fine to drop support for MediaWiki older than 39

**Comment by squirrelslair** [comment]
I just ran into this as well when I tried to update my wikis. Is there an ETA for this or an alternative solution?

**Comment by JeroenDeDauw** [comment]
Seems like the one open TODO is to rebase this PR against master

**Comment by squirrelslair** [comment]
Has the fix been added to the main version of SMW, and if not, do we know when that will happen? Thanks!

**Comment by gesinn-it-gea** [comment]
@Sheep-y can you please rebase and check if tests are passing

**Comment by paladox** [comment]
Bump :)

(any progress on this?)

**Comment by paladox** [comment]
@Sheep-y can you rebase please?

**Comment by paladox** [comment]
Is this still needed?

**Comment by squirrelslair** [comment]
> Is this still needed?

Not for me, I started to use the newest version via git of all these things and it hasn't had this problem for a while. Thanks for asking.

**Comment by alistair3149** [comment]
> If this PR is no longer relevant, perhaps it can be closed.

It might still be relevant since I can reproduce the `Exception caught: Table name component contains unexpected quote or dot character` error on 1.43.

**Comment by paladox** [comment]
Is it expected that this is merged into a separate branch?

**Comment by alistair3149** [comment]
> Is it expected that this is merged into a separate branch?

Yes this is merged into a separate branch so that fixes can be applied on top of it.
See https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5953
