### PR TITLE
Fix and improve maintenance log entries

### LINKED ISSUE #6146: Fix maintenance log entries
### Setup

- [MediaWiki](https://www.mediawiki.org/)	[1.43.1](https://www.mediawiki.org/wiki/MediaWiki_1.43) [(58cb2a9)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/58cb2a9ed407d25e52d34050b5d18fd94cec8bc4) 11:46, 15 June 2025
- [PHP](https://php.net/)	8.2.28 (apache2handler)
- [MariaDB](https://mariadb.org/)	10.11.11-MariaDB-0+deb12u1
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	5.0.2

### Issue

When running maintenance scripts with the `--with-maintenance-log` the script run gets logged. When introduced the log would e.g. read for SMW 3.2.3 

13:01, 15 June 2025 [DisposeOutdatedEntitiesLogger](https://www.semantic-mediawiki.org/w/index.php?title=User:DisposeOutdatedEntitiesLogger&action=edit&redlink=1) ([talk](https://www.semantic-mediawiki.org/w/index.php?title=User_talk:DisposeOutdatedEntitiesLogger&action=edit&redlink=1) | [contribs](https://www.semantic-mediawiki.org/wiki/Special:Contributions/DisposeOutdatedEntitiesLogger) | [block](https://www.semantic-mediawiki.org/wiki/Special:Block/DisposeOutdatedEntitiesLogger)) maintenance ({"Memory used":5933288,"Time used":"0.47 sec"})

Nowadays, it reads for SMW 5.0.2

[21:50, 15 June 2025](https://sandbox.semantic-mediawiki.net/w/index.php?title=Sp%C3%A9cial:Journal&logid=31981) [DisposeOutdatedEntitiesLogger](https://sandbox.semantic-mediawiki.net/wiki/Utilisateur:DisposeOutdatedEntitiesLogger) [talk](https://sandbox.semantic-mediawiki.net/w/index.php?title=Discussion_utilisateur:DisposeOutdatedEntitiesLogger&action=edit&redlink=1) [contribs](https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:Contributions/DisposeOutdatedEntitiesLogger) [block](https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:Bloquer/DisposeOutdatedEntitiesLogger) performed unknown action "smw/maintenance" on [DisposeOutdatedEntitiesLogger](https://sandbox.semantic-mediawiki.net/w/index.php?title=DisposeOutdatedEntitiesLogger&action=formedit&redlink=1) ({"Memory used":4153904,"Time used":"2.05 sec"})

To cut a long story short, ti would be nice to get back `maintenance` instead of `performed unknown action "smw/maintenance"`.

### PR DESCRIPTION
**Pull request by alistair3149**
image

## Summary

Fixes #6146 — maintenance log entries displayed as `performed unknown action "smw/maintenance"` instead of a proper message.

**Root cause:** No `LogActionsHandlers` entry in `extension.json` for `smw/maintenance`, so MediaWiki didn't know which `LogFormatter` to use.

**Changes:**
- Register `LogActionsHandlers` mapping `smw/maintenance` → `LogFormatter` in `extension.json`
- Update `logentry-smw-maintenance` to use the standard `LogFormatter` message format with `$1` (performer) and `{{GENDER}}` support for translators
- Format maintenance log comments as human-readable text instead of raw JSON, with memory values converted to human-readable units (KB/MB/GB)

**Before:**
> DisposeOutdatedEntitiesLogger performed unknown action "smw/maintenance" on DisposeOutdatedEntitiesLogger ({"Memory used":3780696,"Time used":"0.04 sec"})

**After:**
> DisposeOutdatedEntitiesLogger (talk | contribs) performed maintenance (Memory used: 3.61 MB, Time used: 0.04 sec)

## Test plan
- [x] Run a maintenance script with `--with-maintenance-log` (e.g. `disposeOutdatedEntities`)
- [x] Check `Special:Log/smw` — entries should show "performed maintenance" with human-readable stats
- [x] Run `composer analyze` — no new warnings
- [x] Run `ManualEntryLoggerTest` and `MaintenanceLoggerTest` — all pass

### CODE REVIEW

File: src/Maintenance/MaintenanceLogger.php [hunk 1]
```diff
@@ -56,7 +56,42 @@ public function logFromArray( array $message, $target = '' ): void {
...
+				$value = self::formatBytes( (int)$value );
+			}
+
+			$parts[] = "$key: $value";
+		}
+
+		return implode( ', ', $parts );
+	}
+
+	private static function formatBytes( int $bytes ): string {
```
Comment (alistair3149) [inline src/Maintenance/MaintenanceLogger.php:81]: Since time used is formatted to human readable, let's format the bytes used as well.

File: src/Maintenance/MaintenanceLogger.php [hunk 2]
```diff
@@ -56,7 +56,42 @@ public function logFromArray( array $message, $target = '' ): void {
...
+				}
+				$value = json_encode( $value );
+			} elseif ( $key === 'Memory used' ) {
+				$value = self::formatBytes( (int)$value );
+			}
+
+			$parts[] = "$key: $value";
+		}
+
+		return implode( ', ', $parts );
```
Comment (alistair3149) [inline src/Maintenance/MaintenanceLogger.php:78]: Format the JSON into comma-separated list since the log entry is for human
